version: "3.1"

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=crypto
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  front:
    build:
      context: ./front
      dockerfile: ./Dockerfile
    command: pnpm dev
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./front:/app
#  api:
#    build:
#      context: ./api
#      dockerfile: Dockerfile
#    restart: always
#    command: pnpm dev
#    working_dir: /app/api
#    volumes:
#      - ./api:/app/api
#    ports:
#      - "3333:3333"
#
#  nuxt:
#    build:
#      context: ./front
#      dockerfile: ./Dockerfile
#    ports:
#      - "3000:3000"
#      - "24678:24678"
#    volumes:
#        - .:/src
#        - node_modules:/src/node_modules
