name: API

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
    paths:
      - 'api/**'
  pull_request:
    branches:
      - main
    paths:
      - 'api/**'

jobs:
  api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install Docker and Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo systemctl start docker
          sudo systemctl enable docker
          sudo apt-get install -y curl
          curl -L "https://github.com/docker/compose/releases/download/{DOCKER_COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
        env:
          DOCKER_COMPOSE_VERSION: '1.29.2' # Replace with the desired Docker Compose version

      - name: Set up PostgreSQL with Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d

      - run: npm install -g pnpm
        working-directory: ./api

      - run: pnpm install --frozen-lockfile
        working-directory: ./api

      - name: Generate APP_KEY
        run: node ace generate:key
        working-directory: ./api

      - name: Copy .env
        run: cp .env.example .env
        working-directory: ./api

      - name: Run tests
        run: |
          pnpm test
          # Add commands to run tests against the PostgreSQL instance
        working-directory: ./api
